kytos-ng/topology

- requirements/dev.in
- requirements/dev.txt
Fixes #15 
Update `requirements/dev.txt` and `requirements/dev.in` changing kytos with kytos-ng repo.
N/A
> Update requirements to use kytos-ng repo

- main.py
- tests/unit/test_main.py
Fixes #14
Summary
======
Link status changes now include a reason attribute
indicating why the status changed.
Changes
---------
- `notify_status_change` accepts an extra argument `reason` to show why the status changed
- methos calling `notify_status_change` updated to use the `reason` argument
- tests modified to reflect these changes
> Add a reason to link status change event

- README.rst
- main.py
- settings.py
- tests/unit/test_main.py
This PR fixes #11.
Description of the change
-----------------------------
The topology Kytos Napp was refactored to load switches, interfaces, and links on startup, enabling the topology to be available right away instead of waiting for the switches to connect. After this refactoring, some settings were no longer necessary, as well as the code was cleaned up. New tests were created and others were adjusted to reflect this new behavior. A new event was created to report topology loaded.
The coverage increased to 91%.
Thread/Lock mechanism was used to avoid race conditions when saving the switches/interfaces/links to the storehouse, since the napp may experiment many switches to be connected at the same time.
Release notes
---------------
- Refactor topology napp to load the topology on …
> Refactor topology to load switches interfaces and links on startup

- main.py
- tests/unit/test_main.py
Fixes #24 
This PR will decouple the execution of the persistency method when called internally from topology (e.g., to enable/disable interfaces/switches/links) and when called from other Napps (e.g., to enable/disable LLDP interface's attribute from Kytos-ng/of_lldp Napp). By doing so, we can guarantee that the storehouse persistency event will be registered on Kytos buffers when returning the user request. So that, if the user shutdown Kytos right away after receiving a 200 status code, her/his request will still be persistent.
- Fix a condition where some user requests to change the administrative state of interfaces/links/switches can be lost if Kytos shut down right after the 200 response being received by the user.
> Decouple execution of administrative state persistency from topology itself and other napps via listen to events

- main.py
- tests/integration/test_main.py
- tests/unit/test_main.py
Fixes #26 
Heads up: this PR was built on top of PR #28 (which has to land first)
Due to the way kytos-ng/topology was doing the persistency of metadata changes/user-requests, it can leads to lost of information when kytos shutdown right after returning a success status code to the user (see Issue #26).
To fix this eventual undesired behavior, I've removed the KytosEvent `kytos/topology.{entities}.metadata.{action}` and added calls to `self.save_metadata_on_store()` directly. Indeed, the Kytos event `kytos/topology.{entities}.metadata.{action}` was just used internally by kytos-ng/topology and there was no benefit on keep using it.
Unit and integration tests were updated to reflect this new metadata persistency route.
End-to-end tests were run using this new approach and no failure was …
> [Fix] Simplify the process to persist metadata changes to avoid data loss

- CHANGELOG.rst
- kytos.json
- main.py
- setup.py
- tests/unit/test_main.py
Fixes #21 
```
[3.7.3] - 2021-12.21
```
- Changed ``add_links`` to only notify a topology update if a link has been created. 
- Changed ``_get_link_or_create`` to also return whether or not a new link has been created.
Notice the periodic topology update events in the same frequency as `.*.interface.is.nni` are received:
```
kytos $> 2021-12-21 12:40:44,246 - INFO [kytos.napps.kytos/pathfinder] (ThreadPoolExecutor-0_61) Topology graph updated.
2021-12-21 12:40:44,260 - INFO [kytos.napps.kytos/pathfinder] (ThreadPoolExecutor-0_61) Topology graph updated.
2021-12-21 12:40:44,316 - INFO [kytos.napps.kytos/pathfinder] (ThreadPoolExecutor-0_228) Topology graph updated.
2021-12-21 12:40:44,323 - INFO [kytos.napps.kytos/pathfinder] (ThreadPoolExecutor-0_119) Topology graph updated.
2021-12-21 …
```
> [Fix] `add_links` to only trigger a topology update if it's a new `Link`

- settings.py
- storehouse.py
- tests/unit/test_storehouse.py
Fixes #31 
The complete description of the problem was detailed in Issue #31. This PR will change the `topology.storehouse.save_status()` method to use a busy wait approach, in which the save status request will stay waiting for the storehouse update callback (up to a certain time) and can confirm the data was stored before returning to the user request.
The proper unit tests were created to validate the new approach.
New round of end-to-end tests were executed to validate if the new solution would actually fix the original issue. Out of 400 executions of the test [tests/test_e2e_05_topology.py::TestE2ETopology::test_030_disabling_switch_persistent](https://github.com/amlight/kytos-end-to-end-tests/blob/master/tests/test_e2e_05_topology.py#L130-L154), no fail was reported.
```
( for i in …
```
> Using a busy wait approach when saving topology status

- CHANGELOG.rst
- kytos.json
- main.py
- setup.py
- tests/unit/test_main.py
Fixes #35 
```
[3.8.0] - 2021-12-22
```
- Fixed ``handle_link_down`` to also deactivate the interface
Now the same diff as presented in the original issue is correct, notice that `00:00:00:00:00:00:00:02:2"` is also down, because it's the other end of the veth pair see the `LOWERLAYERDOWN` below for more info: 
```
--- before.json 2021-12-22 11:38:02.277432565 -0300
+++ after.json  2021-12-22 11:38:20.427448498 -0300
@@ -68,10 +68,10 @@
"metadata": {}
},
"cf0f4071be426b3f745027f5d22bc61f8312ae86293c9b28e7e66015607a9260": {
-                "active": true,
+                "active": false,
"enabled": true,
"endpoint_a": {
-                    "active": true,
+                    "active": false,
"enabled": true,
"id": "00:00:00:00:00:00:00:02:2",
"link": …
```
> [Fix] Fixed handle_link_down to deactivate interface

- CHANGELOG.rst
- kytos.json
- main.py
- setup.cfg
- setup.py
- tests/integration/test_main.py
- tests/unit/test_main.py
Fixes #42 
version `[3.10.0] - 2022-01-19`
- Changed ``_load_link`` to try to also load interface available tags
- Changed ``save_status_on_storehouse`` to also store interface available_tags
- Subscribed to ``kytos/*.link_available_tags`` events
- Added ``_load_intf_available_tags`` to try to load and set available_Tags
- Added ``_get_links_dict_with_tags`` to also have interface available_tags
- Hooked ``_load_intf_available_tags`` to be called for interface_created
I've simulated the following exploratory test:
- Created a L2VPN, to make sure it used a tag, so links would have 4094 tags available
- Forced a reconnection, when switches reconnected it loaded correctly the number of available tags
- Removed a L2VPN to make sure it was also freeing the tag correctly (back to 4095 tags) …
> [Fix] Added support to store and load interface `available_tags`

- CHANGELOG.rst
- kytos.json
- main.py
- setup.py
- tests/unit/test_main.py
Fixes #47 
link_down event wasn't being published when the interfaces went down simultaneously
- ``handle_link_down`` to publish link_down
- ``add_links`` to also notify link_up
- ``last_status_is_active`` metadata to ensure single notification
- When a reboot happens, notice that mef_eline got a single notification event `mef_eline got kytos/topology.link_down *`
```
2022-01-20 18:15:52,078 - INFO [kytos.napps.kytos/of_core] (ThreadPoolExecutor-0_0) The port 1 from switch 00:00:00:00:00:00:00:01 was deleted, reason OFPPR_DELETE.
2022-01-20 18:15:52,113 - INFO [kytos.napps.kytos/of_core] (ThreadPoolExecutor-0_9) Modified Interface('s2-eth1', 1, Switch('00:00:00:00:00:00:00:02')) 00:00:00:00:00:00:00:02:1
2022-01-20 18:15:52,114 - INFO [kytos.napps.kytos/of_core] (ThreadPoolExecutor-0_9) …
```
> [Fix] link_down event isn't being published if the interfaces go down simultaneously

- CHANGELOG.rst
- kytos.json
- main.py
- setup.py
- tests/unit/test_main.py
Fixes #49 
Fixed calling `notify_topology_update()` when interface goes down/up or when entities are disabled/enabled, just so subscribers like `pathfinder` have the updated graph. 
- Hooked ``notify_topology_update`` to be called at least once if an interface goes up or down
- Updated rest endpoints that disable entities to notify topology update
- Updated rest endpoints that enable entities to notify topology update
- Changed status code from 409 to 404 when interfaces aren't found
> [Fix] call `notify_topology_update()` when interface goes down/up or when entities are disabled/enabled

- setup.py
pytest has dropped for py3.6, as mentioned on [kytos issue 193](https://github.com/kytos-ng/kytos/issues/193), so this is PR freezes pytest version in the meantime until we drop support for py3.6 and upgrade the unit tests to run on newer python version as we have mapped on `epic_ci`.
> Freeze pytest version to be compatible with py3.6 

- ui/k-info-panel/switch_info.kytos
This PR is needed for UI PR [#26](https://github.com/kytos-ng/ui/pull/26) based on issue [#14](https://github.com/kytos-ng/ui/issues/14)
The `content.interfaces` from `k-info-panel/switch_info` was not updating. So, now `interfaces` array is updated from an api call. Probably a temporal solution.
> Fix interface details not updating

- tests/integration/helpers.py
This integration test was passing before, thanks to the cached `id` property PR that has landed https://github.com/kytos-ng/kytos/pull/243 the error became evident here in this test case. ` tox` exec:
```
❯ tox
GLOB sdist-make: /home/viniarck/repos/topology/setup.py
py39 inst-nodeps: /home/viniarck/repos/topology/.tox/.tmp/package/1/kytos_topology-2022.1.0.zip
py39 installed: astroid==2.9.3,attrs==21.4.0,backcall==0.1.0,black==22.3.0,blinker==1.4,certifi==2021.10.8,click==8.1.3,coverage==6.2,decorator==4.4.2,distlib==0.3.4,docopt==0.6.2,docuti
ls==0.19,elastic-apm==6.9.1,filelock==3.4.1,Flask==1.1.2,Flask-Cors==3.0.8,Flask-SocketIO==4.2.1,iniconfig==1.1.1,ipython==7.13.0,ipython-genutils==0.2.0,isort==5.10.1,itsdangerous==1.1.
0,janus==0.4.0,jedi==0.16.0,Jinja2==2.11.1,-e …
```
> Fix failing integration test

- CHANGELOG.rst
- README.rst
- controllers/__init__.py
- main.py
- tests/integration/test_main.py
- tests/unit/test_main.py
Fixes #69 
This PR implements the integration with link liveness events as described on this blueprint https://github.com/kytos-ng/kytos/pull/241. The link liveness events from topology's perspective are protocol agnostic, when the time comes to also have liveness via BFD it's expected to be similar as long as we reuse the same event patterns in the future. 
- Topology now reacts to link liveness detection events.
- ``kytos/topology.link_up`` is only published if link.status is EntityStatus.UP, which takes into account other protocol logical states.
- I'm using a linear topology with 2 switches, once `kytos/.*.liveness.up` is received liveness goes up, and notice that `mef_eline` handles it as a link up:
```
2022-07-08 12:01:44,526 - INFO [kytos.napps.kytos/topology] (thread_pool_app_4) …
```
> [Feature] Subscribed to link liveness events

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Fixes https://github.com/kytos-ng/pathfinder/issues/24
Send topology.switches and topology.links shallow copy on events:
- kytos/topology.topology_loaded
- kytos/topology.updated
I've also updated `kytos/topology.{entities}.metadata.{action}` to end a shallow copy, otherwise [on pathfinder](https://github.com/kytos-ng/pathfinder/blob/master/main.py#L217) it could result in issues too
Thanks for catching this @italovalcy, in the future, let's augment our docs with more best practices for this type of issue for developers who are creating/maintaining events.
> Send topology.switches and topology.links shallow copy on events

- CHANGELOG.rst
- main.py
Fixes #107 
- Shallow copy shared iterables that are used on REST endpoints
- Refactored previous shallow copies to use `.copy()` to make the intention and code clearear
The underlying issue, as explicit summarized in the exception, is related to a shared memory data struct being changed while it's being iterated (a best practice in kytos-ng docs to avoid this will be addressed on https://github.com/kytos-ng/kytos-ng.github.io/issues/33):
- Here's a minimal example with two temporary functions that iterate on a shared iterable `controller.switches` (self.switches), and intentionally `switches_iter_changing_size` will insert into the collection to simulate the issue, whereas `switches_iter_copy_changing_size` will make a shallow copy and iterate on it, while inserting into the original …
> [Fix][Issue 107] RuntimeError: dictionary changed size during iteration

- CHANGELOG.rst
- README.rst
- main.py
- tests/integration/test_main.py
- tests/unit/test_main.py
This is for helping out to fix this current issue that was caught on e2e tests, it'll provide a way to get and publish the current topology for reconciliation, although this doesn't fix the root cause it'll provide a recovery mechanism, and if it keeps happening with better instrumentation/logs on pathfinder we'll be able to catch (race conditions weren't spotted yet):
https://github.com/amlight/kytos-end-to-end-tests/issues/179
- Publish event ``kytos/topology.current`` for topology reconciliation
- Subscribed to event ``kytos/topology.get`` to publish the current topology
> [Feature] Added event to publish the current topology when requested

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Fixes #101 
Fixes #100 
Fixes #103 (it's using `notified_up_at` metadata though)
- Fixed link up to only notify when ``LINK_UP_TIMER`` has passed
- Hooked ``link_status_hook_link_up_timer`` to update ``status`` accordingly.
- Added ``notified_up_at`` internal reserved metadata
Now it's correctly respecting ``LINK_UP_TIMER``, the following cases were explored locally (I've also left some requests to pathfinder in the background running for additional testing):
> I'll dispatch e2e tests execution with this branch. `LINK_UP_TIMER` is 1 sec there, so no surprises expected, once I have the results I'll post here for completeness. 
1 - Both interface go up and created in a short period:
Notice that `mef_eline` is notified in 10 secs more of less `[2022-11-18 14:43:30,776 - INFO …
> [Fix] Link up notifications `LINK_UP_TIMER`

- CHANGELOG.rst
- README.rst
- main.py
- tests/integration/test_main.py
- tests/unit/test_main.py
Closes #71 
- Added switch links enable/disable notifications
- Added interface links enable/disable notifications
> Added notification methods

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Fixes #113 
- Load interfaces as inactive
This PR is on top of #114 and it should be merged after Aldo's PR #115 (to facilitate merging things in order)
I've explored it simulating the original issues, and with mef_eline and link liveness enabled. It behaved as expected, since interfaces are initially loaded as inactive, they only will turn into active when handling port description or port status (when handling port description I found another issue though https://github.com/kytos-ng/of_core/issues/89):
Here's the topology output with the interfaces disabled when the topology gets loaded:
```
{
"topology": {
"links": {
"cf0f4071be426b3f745027f5d22bc61f8312ae86293c9b28e7e66015607a9260": {
"active": false,
"enabled": true,
"endpoint_a": {
"active": false,
...
},
"switches": { …
```
> [Fix] Load interfaces as inactive

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
This is related to https://github.com/kytos-ng/of_core/pull/90, 
It turns out that the event of interface creation was also assuming that the interface being created was active:
- Created interface should only be activated if it's active
- Fixed last_status_is_active when both interfaces go down to notify only once
Local tests were explored in the PR linked.
> [Fix] `handle_interface_created` should only activate if interface is active

- main.py
- tests/unit/test_main.py
This PR is intended to provide compatibility with kytos-ng/maintenance#64, which updates the format of events for maintenance windows to use device ids. Should kytos-ng/maintenance#64 be accepted, this PR should be accepted along with it.
> Maintenance compatibility update

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Closes https://github.com/kytos-ng/of_core/issues/118
This fixes a major issue that @italovalcy has hit during the prod deployment, so I ended up prioritizing this fix to avoid blocking the prod deployment. I'll send a PR backporting this shortly.
- Rejected unordered late preempted interface events to avoid state inconsistencies
- Essentially, this fix is analogous to https://github.com/kytos-ng/pathfinder/pull/35/files. It turns out that we do have order guarantees from our core queues, but thread pool based handlers aka `@listen_to`, their threads can get preempted and based on non deterministic scheduling from threads you can end up in this case, this becomes more evident in cases where there's too many events, so whenever a shared resource like interface state is vulnerable to this …
> fix: rejected unordered late preempted interface events to avoid state inconsistencies

- CHANGELOG.rst
- kytos.json
- main.py
- tests/unit/test_main.py
Backported from https://github.com/kytos-ng/topology/pull/132, the summary and local tests are the same and the other PR so check out there.
@italovalcy, let me know if you can try out this backported branch `fix/unordered_intf_events_backport_2022.3` in the next days. I've dispatched e2e for the other PR, but it should be the same expected result. Appreciated your help and good catch. Once this lands then we'll push a tag `2022.3.1` on top of `base/2022.3.1` branch that this PR is targeting.
> [2022.3.1] fix: rejected unordered late preempted interface events to avoid state inconsistencies

- CHANGELOG.rst
- controllers/__init__.py
- main.py
- tests/unit/test_main.py
- tests/unit/test_topo_controller.py
Closes #139 (impacting prod) and #140 (it's explained in the issue the reason why)
See updated changelog file
Trying to simulate and force the race condition with a `time.sleep` doesn't result in the issue anymore:
```
kytos $> 2023-06-19 12:28:57,925 - INFO [kytos.napps.kytos/of_core] [main.py:708:update_port_status] (MainThread) PortStatus modified interface 00:00:00:00:00:00:00:01:4 state 0       
2023-06-19 12:28:57,926 - INFO [kytos.napps.kytos/of_core] [main.py:708:update_port_status] (MainThread) PortStatus modified interface 00:00:00:00:00:00:00:01:4 state OFPPS_LINK_DOWN
2023-06-19 12:28:57,927 - INFO [kytos.napps.kytos/of_core] [main.py:708:update_port_status] (MainThread) PortStatus modified interface 00:00:00:00:00:00:00:03:3 state 0
2023-06-19 12:28:57,928 - INFO …
```
> fix: Fixed interface and link activation/deactivation race condition

- CHANGELOG.rst
- main.py
- tests/integration/test_main.py
- tests/unit/test_main.py
This PR removes the old maintenance handlers, which have been replaced with the interruption handlers. This should resolve the following issues with associated with the old maintenance handlers:
- kytos-ng/topology#64
- kytos-ng/topology#62
- kytos-ng/topology#8
- kytos-ng/topology#87
Local tests were performed with kytos-ng/maintenance#78. With this patch, maintenace windows continued to propely dispatch link up and link down events when maintenance windows began and ended.
All maintenance related end to end tests pass. Here are the results:
```
kytos-end-to-end-tests-kytos-1  | Starting enhanced syslogd: rsyslogd.
kytos-end-to-end-tests-kytos-1  | /etc/openvswitch/conf.db does not exist ... (warning).
kytos-end-to-end-tests-kytos-1  | Creating empty database /etc/openvswitch/conf.db. …
```
> Removed old maintenance handlers

- CHANGELOG.rst
- README.rst
- main.py
- tests/integration/test_main.py
- tests/unit/test_main.py
This is needed for https://github.com/kytos-ng/pathfinder/pull/55
I'll send a PR backporting soon
See updated changelog file 
Executed on https://github.com/kytos-ng/pathfinder/pull/55
Executed on https://github.com/kytos-ng/pathfinder/pull/55
> feat: publish `kytos/topology.update` when changing link metadata

- CHANGELOG.rst
- README.rst
- kytos.json
- main.py
- tests/integration/test_main.py
- tests/unit/test_main.py
This is backport from https://github.com/kytos-ng/topology/pull/150, check [PR 150](https://github.com/kytos-ng/topology/pull/150) out for more information.
> [release 2022.3.3] feat: publish `kytos/topology.update` when changing link metadata

- CHANGELOG.rst
- README.rst
- controllers/__init__.py
- db/models/__init__.py
- main.py
- openapi.yml
- requirements/dev.in
- scripts/README.md
- scripts/vlan_pool.py
- tests/integration/test_main.py
- tests/unit/test_main.py
- tests/unit/test_topo_controller.py
Closes #157 
Changed DB `interface_details` to:
```
{
_id: '00:00:00:00:00:00:00:02:2',
available_vlans: { '1': [ [ 1, 499 ], [ 501, 4095 ] ] },
id: '00:00:00:00:00:00:00:02:2',
inserted_at: ISODate("2023-08-28T17:05:42.238Z"),
tag_ranges: { '1': null }
},
```
Added API requests to replace `vlan_pool` settings
- Added request DELETE `v3/interfaces/{interface_id}/tag_ranges` with accepted parameter `tag_type`.
- Added request POST `v3/interfaces/{interface_id}/tag_ranges`. Body accepted example `{"1": [[100, 4000]]}`.
- Adapted NApp from `tag_type` interger to string
Sent requests with the added URLs
Unit tests added
This PR is part of the epic [epic_topology_vlanpool](https://github.com/search?q=org%3Akytos-ng+is%3Aissue+label%3Aepic_topology_vlanpool). 
E2E tests are passing, …
> feature: Added endpoints to set and delete `tag_range`

- CHANGELOG.rst
- main.py
- openapi.yml
- requirements/dev.in
- tests/unit/test_main.py
Closes #162 
This is based on the branch `epic/vlan_pool` which is not going to be modified.
Added endpoints:
- `GET v3/interfaces/{interface_id}/tag_ranges`
- `GET v3/interfaces/tag_ranges`
Called these new API endpoints
Added unit tests
N/A
Note:
Tox is passing
> feature: Added get endpoints for Interface tag ranges

- scripts/vlan_pool.py
Closes #170 
Script `vlan_pool.py` no longer includes archived EVCs so their tag is added to `interface_details`
Executed script
> Filtered out archived EVCs

- CHANGELOG.rst
- README.rst
- kytos.json
- main.py
- scripts/README.md
- scripts/uni_tag_allocation.py
- tests/integration/test_main.py
- tests/unit/test_main.py
Closes #165 
The base branch is `base/2023.1.0`, It is what we have on [releases](https://github.com/kytos-ng/topology/releases).
Added `kytos/.*.uni_available_tags` so `Interface.available_tags` is updated in the DB when a UNI tag is allocated
Added uni tests
Created EVCs and see allocated vlan from interfaces.
Results in `mef_eline` [PR](https://github.com/kytos-ng/mef_eline/pull/381)
> backport: `kytos/.*.uni_available_tags` to update UNI tags in interfaces

- tests/unit/test_model.py
- tests/unit/test_topo_controller.py
Related to https://github.com/kytos-ng/kytos/issues/376
- Refactored `unittest.TestCase` as pytest unit tests
- No need to update the changelog either for this case
Not needed
Not needed
> chore: refactored `unittest.TestCase` as pytest unit tests

- main.py
- requirements/dev.in
- tests/unit/test_main.py
Closes #174 
Moved `_get_tag_ranges()` to `kytos/core/tag_ranges.py`
Now using `KytosInvalidRanges` exception
This PR relies in kytos PR [#428](https://github.com/kytos-ng/kytos/pull/428)
Unit tests are moved to `kytos/core`
```
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.3.0
rootdir: /tests
plugins: timeout-2.1.0, rerunfailures-10.2, anyio-3.6.2
collected 244 items
tests/test_e2e_01_kytos_startup.py ..                                    [  0%]
tests/test_e2e_05_topology.py ..................                         [  8%]
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 24%]
tests/test_e2e_11_mef_eline.py ......                                    [ 27%] …
```
> Moved `_get_tag_ranges()` to kytos/core

- CHANGELOG.rst
- controllers/__init__.py
- db/models/__init__.py
- main.py
- openapi.yml
- requirements/dev.in
- scripts/README.md
- scripts/special_vlan_allocation.py
- scripts/vlan_pool.py
- tests/unit/test_db_models.py
- tests/unit/test_main.py
- tests/unit/test_topo_controller.py
Closes #177 
Added `special_available_tags` to `interface_details`
Related kytos [PR](https://github.com/kytos-ng/kytos/pull/431)
Added unit tests
Create EVCs with special vlans and restarted kytos
```
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.3.0
rootdir: /tests
plugins: timeout-2.1.0, rerunfailures-10.2, anyio-3.6.2
collected 244 items
tests/test_e2e_01_kytos_startup.py ..                                    [  0%]
tests/test_e2e_05_topology.py ..................                         [  8%]
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 24%]
tests/test_e2e_11_mef_eline.py ......                                    [ 27%]
tests/test_e2e_12_mef_eline.py .....Xx. …
```
> Added `special_available_tags` to `interface_details`

- CHANGELOG.rst
- README.rst
- controllers/__init__.py
- main.py
- openapi.yml
- tests/unit/test_main.py
- tests/unit/test_topo_controller.py
Closes #154
Added an endpoint to delete a link
Added unit tests
Deleted a link that was previously removed with `link s1 s3 down` on mininet console.
> Added endpoint to delete link

- CHANGELOG.rst
- main.py
- tests/unit/test_main.py
Closes #186 
See updated changelog file 
I repeated the same test mentioned on issue 186, no longer the problem happens, notice below as soon as the switch reconnects the link_down gets notified now if an interface is deactivated when a switch is disabled:
```
kytos $> 2024-03-01 14:18:11,771 - INFO [kytos.core.atcp_server] (MainThread) Connection lost with client 127.0.0.1:36958. Reason: Request closed by client                              
2024-03-01 14:18:16,106 - INFO [kytos.core.atcp_server] (MainThread) Connection lost with client 127.0.0.1:36962. Reason: Request closed by client
kytos $>                                                                                                                                                                                 
kytos $> 2024-03-01 …
```
> fix: handled deactivated interface when an interface gets created.

- CHANGELOG.rst
- db/models/__init__.py
- tests/unit/test_db_models.py
Related to https://github.com/kytos-ng/of_core/pull/133
This PR is on top of https://github.com/kytos-ng/topology/pull/187
- This PR isn't absolutely needed since it's been fixed on of_core, and the existing paths before creating an interface will set it, but since on kytos runtime an [`Interface.speed` can still be None](https://github.com/kytos-ng/kytos/blob/master/kytos/core/interface.py#L688), then for completeness let's keep the DB model also supporting it. If one day a new southbound doesn't set it it also won't crash. 
- See updated changelog file
Same as the tests mentioned on the linked PR
I'll dispatch an e2e exec with this branch and of_core's linked PR:
```
+ python3 -m pytest tests/ --reruns 2 -r fEr
============================= test session starts …
```
> fix: allowed interface speed to be null on switches collection

- CHANGELOG.rst
- controllers/__init__.py
- main.py
- openapi.yml
- tests/integration/test_main.py
- tests/unit/test_main.py
- tests/unit/test_topo_controller.py
Closes #191
Added API request to delete interface `DELETE api/kytos/topology/v3/interfaces/00:00:00:00:00:00:00:01:1`.
After the `*.*.switch.interface.deleted` event, the interface can be deleted from memory if it is not used.
To delete interface, it needs to be removed from OVS: `sudo ip link delete s1-eth4`
Also:
- It is inactive and disabled.
- It does not have a link.
- There should not be an installed flow related to the interface (actions `output`, instructions `apply_action` and match `in_port`).
TBA
> Added interface deletion

- CHANGELOG.rst
- kytos.json
- main.py
- setup.py
Closes #205 
To duplicate the issue with a high rate of success, this method is needed inside the class `Interface`:
```
def testing3(self, controller, n):
for i in range(n):
self.available_tags = {"vlan": [[i, 4095]]}
self._notify_interface_tags(controller)
```
And this can be called from kytos console preferably with a high value number:
```
controller.switches['00:00:00:00:00:00:00:01'].interfaces[1].testing3(controller, 200)
```
Also, only works after a kytos shutdown. It has to be a fresh start.
Performed the above test multiple times
```
+ python3 -m pytest tests/ --reruns 2 -r fEr
============================= test session starts ==============================
platform linux -- Python 3.11.2, pytest-8.1.1, pluggy-1.5.0
rootdir: /tests
plugins: rerunfailures-13.0, timeout-2.2.0, …
```
> Moved controller method inside lock

- CHANGELOG.rst
- kytos.json
- main.py
- tests/unit/test_main.py
Closes https://github.com/kytos-ng/mef_eline/issues/503
Closes #158 
See updated changelog file 
- The original bug I didn't manage to reproduce. 
- I found another related adjacent one that seems the cause, and that one no longer reproduces as [mentioned here](https://github.com/kytos-ng/mef_eline/issues/503#issuecomment-2341456265)
- I've also run 2 x hundreds of link flaps and the link status always remained correct and the events were notified as expected
```
def main() -> None:
"""Main function."""
link_flap_iters = 500
interfaces = ["s1-eth4"]
link_id = "c8b55359990f89a5849813dc348d30e9e1f991bad1dcb7f82112bd35429d9b07"
wait_for = 10
test_iters = 5
for test_iter in range(test_iters):
print(f"link_flap test iteration {test_iter}")
assert_topology_link_up(link_id)
for i in …
```
> hotfix 2024.1.2: increased acquired lock scope when handling link up|down 

- CHANGELOG.rst
- kytos.json
- main.py
- tests/integration/test_main.py
- tests/unit/test_main.py
Closes #155
Replaces the existing event handlers for interruptions with a single event handler using the dynamic_single pool.
Interruptions appear to be processed by topology in a similar fashion as before.
Here are the E2E results:
```
kytos_1        | Starting enhanced syslogd: rsyslogd.
kytos_1        | /etc/openvswitch/conf.db does not exist ... (warning).
kytos_1        | Creating empty database /etc/openvswitch/conf.db.
kytos_1        | Starting ovsdb-server.
kytos_1        | Configuring Open vSwitch system IDs.
kytos_1        | Starting ovs-vswitchd.
kytos_1        | Enabling remote OVSDB managers.
kytos_1        | + '[' -z '' ']'
kytos_1        | + '[' -z '' ']'
kytos_1        | + echo 'There is no NAPPS_PATH specified. Default will be used.'
kytos_1        | There is no …
```
> Switch interruptions to use dynamic_single for handling

- scripts/db/2023.2.0/000_vlan_pool.py
- scripts/db/2023.2.0/README.md
Closes #213 
This Pull request adds support for custom tag range on vlan pool migration script.
N/A
N/A
> Add support for custom tag range on vlan pool migration script

- CHANGELOG.rst
- kytos.json
- main.py
Closes #215 
See updated changelog file 
- Created an inter EVC on Kytos-ng version `2023.2` and using this topology branch, exercised one link down, noticed that notification was as expected, including the log message:
```
2024-10-04 16:17:24,180 - INFO [kytos.napps.kytos/mef_eline] (AnyIO worker thread) EVC(e66cc60e6d7849, evpl2) was deployed.
2024-10-04 16:17:24,181 - INFO [uvicorn.access] (MainThread) 127.0.0.1:35806 - "POST /api/kytos/mef_eline/v2/evc/ HTTP/1.1" 201
2024-10-04 16:17:24,186 - INFO [uvicorn.access] (MainThread) 127.0.0.1:35846 - "POST /api/kytos/pathfinder/v3/ HTTP/1.1" 200
2024-10-04 16:17:24,195 - INFO [kytos.napps.kytos/flow_manager] (AnyIO worker thread) Send FlowMod from request dpid: 00:00:00:00:00:00:00:02, command: add, force: False,  flows[0, 2]: [
{'match': …
```
> hotfix 2023.2.1: increased acquired lock scope when handling link up|down

- CHANGELOG.rst
- kytos.json
- main.py
Backport from https://github.com/kytos-ng/topology/pull/227
- For more information check out the linked PR. 
- Unit tests not backported since they aren't run in the CI, and it's the same change as what's already been tested
> [release][backport 2023.2.3] fix: fixed liveness handler potential out of order exec

- ui/k-info-panel/link_info.kytos
- ui/k-info-panel/switch_info.kytos
Closes #225 
Interface was a reserved keyword and it would not be loaded by the Vue JS loader. Because of this `interface` was replaced with `k_interface`.
Changes didn't seem to affect UI as they were just a variable name change.
> UI vue loader fix

- CHANGELOG.rst
- controllers/__init__.py
- kytos.json
Closes https://github.com/kytos-ng/kytos/issues/538
- See updated changelog file 
- Index creation timeout didn't get adjusted since the default is plenty when its first created
Local tests were done with https://github.com/kytos-ng/kytos/pull/541
```
coverage: OK ✔ in 41.32 seconds
lint: recreate env because env type changed from {'name': 'coverage', 'type': 'VirtualEnvRunner'} to {'name': 'lint', 'type': 'VirtualEnvRunner'}
lint: remove tox env folder /home/viniarck/repos/ky20241/topology/.tox/py311
lint: install_deps> python -I -m pip install -r requirements/dev.in
lint: commands[0]> python3 setup.py lint
running lint
Yala is running. It may take several seconds...
INFO: Finished isort
INFO: Finished pycodestyle
INFO: Finished pylint
[isort] Skipped 4 files
:) No issues found.
No …
```
> release 2024.1.5: DB controller now retries for `ExecutionTimeout` and `ConnectionFailure` instead of just `AutoReconnect`

- scripts/console/2025.1.0/001_retire_vlans.py
Closes #246
Accidentally had pushed the range I was using for testing. This PR sets it to the intended default range of [4095, 4095]
Doesn't really change the functionality, just the parameters.
Not appicable to E2E.
> Set default retire_vlans range to [4095, 4095]

- CHANGELOG.rst
- kytos.json
- main.py
- scripts/db/2025.2.0/000_retire_metadata.py
- scripts/db/2025.2.0/README.md
- tests/unit/test_main.py
Backport of  #253 to topology 2024.1.6
Makes it so that the link up handler is more stable when handling successive link ups during a switch reconnect.
Runs as expected. Link ups are handled correctly regardless of the time between the link up, and the switch reconnect.
Haven't rerun the E2E tests on this version, but it was passing on 2025. I can run these tests on request.
> Backport fix for successive link ups during switch connect in kytos 2024

- main.py
Part of resolving kytos-ng/pathfinder#102.
Provides a function, intended to be called by other NApps, which will provide the latest topology.
See kytos-ng/pathfinder#104 for more details on how its being used.
Check the pathfinder PR.
Check the pathfinder PR.
> Add method for other NApps to retrive the latest topology

- CHANGELOG.rst
- kytos.json
- main.py
- tests/integration/test_main.py
- tests/unit/test_main.py
Closes #264
Mismatched links are treated as new links
Added warning for mismatched links
Deploy 2 topologies with overlapping links.
Fix and run unit tests
N/A
> Backport: Log a warning for mismatched links 2023.2

- CHANGELOG.rst
- main.py
- requirements/dev.in
- tests/unit/test_main.py
Closes #258
Updated PR with other recent changes to `topology`
Moved links dictionary to `kytos/core` so they can be accessed from `controller` by any NApp
Added unit tests
Performed link flaps
Created EVCs
Run latest updated from E2E including mismatched links.
```
+ python3 -m pytest tests/ --reruns 2 -r fEr
============================= test session starts ==============================
platform linux -- Python 3.11.2, pytest-8.1.1, pluggy-1.6.0
rootdir: /tests
plugins: rerunfailures-13.0, timeout-2.2.0, anyio-4.3.0
collected 284 items
tests/test_e2e_01_kytos_startup.py ..                                    [  0%]
tests/test_e2e_05_topology.py ..................                         [  7%]
tests/test_e2e_06_topology.py ....                                       [  8%] …
```
> Moved links to core

- CHANGELOG.rst
- README.rst
- kytos.json
- main.py
- tests/unit/test_main.py
Closes #277 
- See updated changelog file 
- Backport of #278 
Done on https://github.com/kytos-ng/of_lldp/pull/121
Done on https://github.com/kytos-ng/of_lldp/pull/121
> [release 2025.1.3] feat: published 'kytos/topology.interface.deleted' on interface deletion

- CHANGELOG.rst
- README.rst
- main.py
- tests/unit/test_main.py
Closes #285
Added new event to notify interface sta
Exercise `mef_eline` [PR](https://github.com/kytos-ng/mef_eline/compare/master...kytos-ng:mef_eline:feat/interface_status_event?expand=1)
Running all tests plus the ones from this [PR](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/392)
> Added event for interface status changes
